site_name: Xournalpp Advanced Export
repo_url: https://github.com/masongyli/xournalpp-advanced-export
repo_name: masongyli/xournalpp-advanced-export

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.tabbed:
      alternate_style: true
    
  - admonition
  - pymdownx.details

  - attr_list
  - md_in_html

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  - pymdownx.keys   # rendering keyboard keys and combinations

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/masongyli

nav:
  - Home:
    - overview: index.md
  - Getting started:
    - Get started: get-started.md
  - Pipeline:
    - pipeline/index.md
    - Operations:
      - Load: pipeline/operations/load.md
      - Combine: pipeline/operations/combine.md
      - Save: pipeline/operations/save.md
      - Refresh Obsidian image: pipeline/operations/refresh-obsidian-image.md
  - Other configurations:
    - other-configurations/index.md
  
  - Development:
    - Setup: development/setup.md
    - Project Structure: development/project-structure.md
    - Testing: development/testing.md
    - Packaging: development/packaging.md

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
  - git-revision-date-localized:
      enable_creation_date: false
  - git-committers:
      repository: masongyli/xournalpp-advanced-export
      branch: doc
  # - git-authors:
